engines:
  - name: jena-fuseki-5.4.0
    build:
      context: ./engines/jena-fuseki/
      args:
        - JENA_VERSION=5.4.0
    run:
      args: ["--mem", "--update", "--port", "7878", "/bsbm"]
    query_url: "http://localhost:7878/bsbm/query"
    update_url: "http://localhost:7878/bsbm/update"
    upload_url: "http://localhost:7878/bsbm/data"

  - name: oxigraph-memory-0.4.11
    image: ghcr.io/oxigraph/oxigraph:0.4.11
    run:
      args: ["serve", "--location", "0.0.0.0:7878"]
    query_url: "http://localhost:7878/query"
    update_url: "http://localhost:7878/update"
    upload_url: "http://localhost:7878/store?no_transaction"

  - name: rdf4j-5.1.3
    build:
      context: ./engines/rdf4j/
      args:
        - RDF4J_VERSION=5.1.3
    run:
      args: []
    port: 8080
    boot_time_s: 15
    query_url: "http://localhost:8080/rdf4j-server/repositories/bench"
    update_url: "http://localhost:8080/rdf4j-server/repositories/bench/statements"
    upload_url: "http://localhost:8080/rdf4j-server/repositories/bench/statements"

benchmarks:
  - name: BSBM
    build:
      context: ./benchmarks/bsbm/
      args:
        - NUMBER_OF_PRODUCTS=10000
    use_cases:
      - name: explore-16
        command_args:
          ["explore", "16"]
