engines:
  - name: rdf-fusion-0.1.0
    build:
      context: ./engines/rdf-fusion/
    run:
      env:
        DATAFUSION_EXECUTION_TARGET_PARTITIONS: "1"
      args: ["serve", "--bind", "0.0.0.0:7878"]
    query_url: "http://localhost:7878/repositories/default/query"
    update_url: "http://localhost:7878/repositories/default/update"
    upload_url: "http://localhost:7878/repositories/default/data"

  - name: jena-fuseki-5.4.0
    build:
      context: ./engines/jena-fuseki/
      args:
        - JENA_VERSION=5.4.0
    run:
      args: ["--mem", "--update", "--port", "7878", "/bsbm"]
    query_url: "http://localhost:7878/bsbm/query"
    update_url: "http://localhost:7878/bsbm/update"
    upload_url: "http://localhost:7878/bsbm/data"

  - name: rdf4j-5.1.3
    build:
      context: ./engines/rdf4j/
      args:
        - RDF4J_VERSION=5.1.3
    run:
      args: []
    port: 8080
    boot_time_s: 15
    query_url: "http://localhost:8080/rdf4j-server/repositories/bench"
    update_url: "http://localhost:8080/rdf4j-server/repositories/bench/statements"
    upload_url: "http://localhost:8080/rdf4j-server/repositories/bench/statements"

benchmarks:
  - name: BSBM Explore (products=25_000, number_of_clients=24)
    build:
      context: ./benchmarks/bsbm/
      args:
        - NUMBER_OF_PRODUCTS=25000
    use_cases:
      - name: explore-24
        command_args:
          ["explore", "24"]

  - name: BSBM Business Intelligence (products=5_000, number_of_clients=12)
    build:
      context: ./benchmarks/bsbm/
      args:
        - NUMBER_OF_PRODUCTS=5000
    use_cases:
      - name: business-intelligence-12
        command_args:
          ["business-intelligence", "12"]

  - name: Wind Farm (turbines=16)
    build:
      context: ./benchmarks/windfarm/
    use_cases:
      - name: windfarm
        command_args:
          ["windfarm"]
