engines:
  - name: oxigraph-memory-0.4.11
    image: ghcr.io/oxigraph/oxigraph:0.4.11
    run:
      args: ["serve", "--location", "0.0.0.0:7878"]

benchmarks:
  - name: BSBM
    build:
      context: ./benchmarks/bsbm/
      args:
        - NUMBER_OF_PRODUCTS=10000
    use_cases:
      - name: Explore 10k, 16 parallel
        command_args:
          ["explore", "10000", "16", "http://localhost:7878"]
