ARG BRANCH=main

FROM docker.io/rust:1.89-bookworm AS builder
ARG BRANCH
RUN apt update
RUN apt install build-essential cmake -y
RUN git clone --branch $BRANCH --single-branch https://github.com/tobixdev/rdf-fusion.git /rdf-fusion
RUN cargo build --release --manifest-path /rdf-fusion/Cargo.toml --bin rdf-fusion

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /rdf-fusion/target/release/rdf-fusion /usr/local/bin/rdf-fusion

ENTRYPOINT [ "/usr/local/bin/rdf-fusion" ]
CMD [ "--memory-limit", "8192", "serve", "--bind", "0.0.0.0:7878" ]